apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 477364833428.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 477364833428.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: b497895a
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
